mutation ChangePassword($password: String!, $currentPassword: String!) {
  changePassword(password: $password, currentPassword: $currentPassword) {
    ... on ActionResult {
      success
    }
    ... on ValidationResult {
      message
      code
    }
  }
}
