mutation resetPassword($password: String!, $token: String!) {
  resetPassword(password: $password, token: $token) {
    ... on ValidationResult {
      message
      code
    }
    ... on ActionResult {
      success
    }
  }
}
